const TrendingActionTypes = {
  FETCH_TRENDING_START: 'FETCH_TRENDING_START',
  FETCH_TRENDING_SUCCESS: 'FETCH_TRENDING_SUCCESS',
  FETCH_TRENDING_FAILURE: 'FETCH_TRENDING_FAILURE'
}

export default TrendingActionTypes;