const TrendingActionTypes = {
  FETCH_TRENDING_START: 'FETCH_TRENDING_START',
  FETCH_TRENDING_SUCCESS: 'FETCH_TRENDING_SUCCESS',
  FETCH_TRENDING_FAILURE: 'FETCH_TRENDING_FAILURE',
  FETCH_MORE_TRENDING_START: 'FETCH_MORE_TRENDING_START',
  FETCH_MORE_TRENDING_SUCCESS: 'FETCH_MORE_TRENDING_SUCCESS',
  FETCH_MORE_TRENDING_FAILURE: 'FETCH_MORE_TRENDING_FAILURE',
  RESET_TRENDING: 'RESET_TRENDING'
}

export default TrendingActionTypes;