const ReleasesActionTypes = {
  FETCH_RELEASES_START: 'FETCH_RELEASES_START',
  FETCH_LAST_MONTH_SUCCESS: 'FETCH_LAST_MONTH_SUCCESS',
  FETCH_LAST_WEEK_SUCCESS: 'FETCH_LAST_WEEK_SUCCESS',
  FETCH_NEXT_WEEK_SUCCESS: 'FETCH_NEXT_WEEK_SUCCESS',
  FETCH_RELEASES_FAILURE: 'FETCH_RELEASES_FAILURE',
}

export default ReleasesActionTypes;