const ReleasesActionTypes = {
  FETCH_LAST_MONTH_START: 'FETCH_LAST_MONTH_START',
  FETCH_LAST_MONTH_SUCCESS: 'FETCH_LAST_MONTH_SUCCESS',
  FETCH_LAST_MONTH_FAILURE: 'FETCH_LAST_MONTH_FAILURE',
  FETCH_LAST_WEEK_START: 'FETCH_LAST_WEEK_START',
  FETCH_LAST_WEEK_SUCCESS: 'FETCH_LAST_WEEK_SUCCESS',
  FETCH_LAST_WEEK_FAILURE: 'FETCH_LAST_WEEK_FAILURE',
  FETCH_NEXT_WEEK_START: 'FETCH_NEXT_WEEK_START',
  FETCH_NEXT_WEEK_SUCCESS: 'FETCH_NEXT_WEEK_SUCCESS',
  FETCH_NEXT_WEEK_FAILURE: 'FETCH_NEXT_WEEK_FAILURE'
}

export default ReleasesActionTypes;