const GameOverviewTypes = {
  FETCH_GAME_START: 'FETCH_GAME_START',
  FETCH_GAME_SUCCESS: 'FETCH_GAME_SUCCESS',
  FETCH_GAME_FAILURE: 'FETCH_GAME_FAILURE',
  FETCH_SIMILAR_START: 'FETCH_SIMILAR_START',
  FETCH_SIMILAR_SUCCESS: 'FETCH_SIMILAR_SUCCESS',
  FETCH_SIMILAR_FAILURE: 'FETCH_SIMILAR_FAILURE',
  FETCH_YOUTUBE_URL_START: 'FETCH_YOUTUBE_URL_START',
  FETCH_YOUTUBE_URL_SUCCESS: 'FETCH_YOUTUBE_URL_SUCCESS',
  FETCH_YOUTUBE_URL_FAILURE: 'FETCH_YOUTUBE_URL_FAILURE'
}

export default GameOverviewTypes;