const SearchActionTypes = {
  FETCH_SEARCH_START: 'FETCH_SEARCH_START',
  FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_FAILURE: 'FETCH_SEARCH_FAILURE'
}

export default SearchActionTypes;