const GenresActionTypes = {
  FETCH_GENRES_START: 'FETCH_GENRES_START',
  FETCH_GENRES_SUCCESS: 'FETCH_GENRES_SUCCESS',
  FETCH_GENRES_FAILURE: 'FETCH_GENRES_FAILURE',
  FETCH_EXACT_GENRE_START: 'FETCH_EXACT_GENRE_START',
  FETCH_EXACT_GENRE_SUCCESS: 'FETCH_EXACT_GENRE_SUCCESS',
  FETCH_EXACT_GENRE_FAILURE: 'FETCH_EXACT_GENRE_FAILURE',
}

export default GenresActionTypes;