const BestGamesActionTypes = {
  FETCH_BEST_GAMES_START: 'FETCH_BEST_GAMES_START',
  FETCH_TOP_GAMES_SUCCESS: 'FETCH_TOP_GAMES_SUCCESS',
  FETCH_TOP_OF_THE_YEAR_SUCESS: 'FETCH_TOP_OF_THE_YEAR_SUCESS',
  FETCH_TOP_OF_2018_SUCESS: 'FETCH_TOP_OF_2018_SUCESS',
  FETCH_BEST_GAMES_FAILURE: 'FETCH_BEST_GAMES_FAILURE',
}

export default BestGamesActionTypes;