const BestGamesActionTypes = {
  FETCH_TOP_GAMES_START: 'FETCH_TOP_GAMES_START',
  FETCH_TOP_GAMES_SUCCESS: 'FETCH_TOP_GAMES_SUCCESS',
  FETCH_TOP_GAMES_FAILURE: 'FETCH_TOP_GAMES_FAILURE',
  FETCH_TOP_OF_THE_YEAR_START: 'FETCH_TOP_OF_THE_YEAR_START',
  FETCH_TOP_OF_THE_YEAR_SUCESS: 'FETCH_TOP_OF_THE_YEAR_SUCESS',
  FETCH_TOP_OF_THE_YEAR_FAILURE: 'FETCH_TOP_OF_THE_YEAR_FAILURE',
  FETCH_TOP_OF_2018_START: 'FETCH_TOP_OF_2018_START',
  FETCH_TOP_OF_2018_SUCESS: 'FETCH_TOP_OF_2018_SUCESS',
  FETCH_TOP_OF_2018_FAILURE: 'FETCH_TOP_OF_2018_FAILURE'
}

export default BestGamesActionTypes;