const AllGamesActionTypes = {
  FETCH_ALLGAMES_START: 'FETCH_ALLGAMES_START',
  FETCH_ALLGAMES_SUCCESS: 'FETCH_ALLGAMES_SUCCESS',
  FETCH_ALLGAMES_FAILURE: 'FETCH_ALLGAMES_FAILURE'
}

export default AllGamesActionTypes;