const AllGamesActionTypes = {
  FETCH_ALLGAMES_START: 'FETCH_ALLGAMES_START',
  FETCH_ALLGAMES_SUCCESS: 'FETCH_ALLGAMES_SUCCESS',
  FETCH_ALLGAMES_FAILURE: 'FETCH_ALLGAMES_FAILURE',
  FETCH_GENRE_GAMES_START: 'FETCH_GENRE_GAMES_START',
  FETCH_GENRE_GAMES_SUCCESS: 'FETCH_GENRE_GAMES_SUCCESS',
  FETCH_GENRE_GAMES_FAILURE: 'FETCH_GENRE_GAMES_FAILURE'
}

export default AllGamesActionTypes;