const AllGamesActionTypes = {
  FETCH_ALLGAMES_START: 'FETCH_ALLGAMES_START',
  FETCH_ALLGAMES_SUCCESS: 'FETCH_ALLGAMES_SUCCESS',
  FETCH_ALLGAMES_FAILURE: 'FETCH_ALLGAMES_FAILURE',
  FETCH_MORE_GAMES_START: 'FETCH_MORE_GAMES_START',
  FETCH_MORE_GAMES_SUCCESS: 'FETCH_MORE_GAMES_SUCCESS',
  FETCH_MORE_GAMES_FAILURE: 'FETCH_MORE_GAMES_FAILURE',
  FETCH_GENRE_GAMES_START: 'FETCH_GENRE_GAMES_START',
  FETCH_GENRE_GAMES_SUCCESS: 'FETCH_GENRE_GAMES_SUCCESS',
  FETCH_GENRE_GAMES_FAILURE: 'FETCH_GENRE_GAMES_FAILURE',
  FETCH_MORE_GENRE_GAMES_START: 'FETCH_MORE_GENRE_GAMES_START',
  FETCH_MORE_GENRE_GAMES_SUCCESS: 'FETCH_MORE_GENRE_GAMES_SUCCESS',
  FETCH_MORE_GENRE_GAMES_FAILURE: 'FETCH_MORE_GENRE_GAMES_FAILURE',
  RESET_GENRE_AND_ALL_GAMES: 'RESET_GENRE_AND_ALL_GAMES'
}

export default AllGamesActionTypes;